// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/new": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users" | "/users/new" | "/users/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/users.new.tsx": {
    id: "routes/users.new";
    page: "/users/new";
  };
  "routes/users.$id.tsx": {
    id: "routes/users.$id";
    page: "/users/:id";
  };
};